name: Python CI

on:
  push:
    branches:
      - dev
      - pubsub
      - 'feature/*' # Matches any branch starting with 'feature/'
  pull_request:
    branches:
      - dev

permissions:
  contents: read
  id-token: write # Required for authenticating to GCP

jobs:
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install GDAL system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gdal-bin libgdal-dev

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests with pytest
        run: pytest tests/test_prep.py tests/test_search.py

  integration-tests:
    name: Run Integration Tests
    needs: unit-tests # This job only runs if unit-tests succeed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}   

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install GDAL system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gdal-bin libgdal-dev

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run integration tests
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
          GCP_BQ_DATASET: ${{ secrets.GCP_BQ_DATASET }}
          GCP_BUCKET: ${{ secrets.GCP_BUCKET }}
          GCP_PUBSUB_TOPIC_TABLE_JOBS: ${{ secrets.GCP_PUBSUB_TOPIC_TABLE_JOBS }}

        run: pytest tests/test_integration.py
